# Generated by Django 5.1.6 on 2025-11-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Extrait')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='articles/files/', verbose_name='Fichier à télécharger')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Admin', max_length=100, verbose_name='Auteur')),
                ('content', models.TextField(verbose_name='Réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='blog.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Téléchargement',
                'verbose_name_plural': 'Téléchargements',
            },
        ),
    ]
